name = "BasicHFProxy"
uuid = "22e46d4d-44a4-4fb3-9bf8-c2d07dd11e16"
authors = ["William F Godoy <williamfgc@yahoo.com>", "Carsten Bauer <crstnbr@gmail.com>"]
version = "0.1.0"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Atomix = "0.1"
MPI = "0.20"
MPIPreferences = "0.1.7"
SpecialFunctions = "2.2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[targets]
test = ["Test", "MPI", "MPIPreferences"]
