name = "BasicHFProxy"
uuid = "22e46d4d-44a4-4fb3-9bf8-c2d07dd11e16"
authors = ["William F Godoy <williamfgc@yahoo.com>", "Carsten Bauer <crstnbr@gmail.com>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
MPI = "0.20"
SpecialFunctions = "2.2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]